"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from dotenv import load_dotenv
from split_settings.tools import include

load_dotenv()

# Application definition
include(
    'components/base.py',
)

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

include(
    'components/database.py',
)

include(
    'components/localization.py'
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
include(
    'components/static.py'
)
